// <auto-generated />
namespace tainanBeaconAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Exhibtion_time_formatting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Exhibtion_time_formatting));
        
        string IMigrationMetadata.Id
        {
            get { return "201708301747273_Exhibtion_time_formatting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
